export const CREATE_INVENTORYORDER_REQUEST = "CREATE_INVENTORYORDER_REQUEST";
export const CREATE_INVENTORYORDER_SUCCESS = "CREATE_INVENTORYORDER_SUCCESS";
export const CREATE_INVENTORYORDER_FAIL = "CREATE_INVENTORYORDER_FAIL";

export const MY_INVENTORYORDERS_REQUEST = "MY_INVENTORYORDERS_REQUEST";
export const MY_INVENTORYORDERS_SUCCESS = "MY_INVENTORYORDERS_SUCCESS";
export const MY_INVENTORYORDERS_FAIL = "MY_INVENTORYORDERS_FAIL";

export const ALL_INVENTORYORDERS_REQUEST = "ALL_INVENTORYORDERS_REQUEST";
export const ALL_INVENTORYORDERS_SUCCESS = "ALL_INVENTORYORDERS_SUCCESS";
export const ALL_INVENTORYORDERS_FAIL = "ALL_INVENTORYORDERS_FAIL";

export const UPDATE_INVENTORYORDER_REQUEST = "UPDATE_INVENTORYORDER_REQUEST";
export const UPDATE_INVENTORYORDER_SUCCESS = "UPDATE_INVENTORYORDER_SUCCESS";
export const UPDATE_INVENTORYORDER_RESET = "UPDATE_INVENTORYORDER_RESET";
export const UPDATE_INVENTORYORDER_FAIL = "UPDATE_INVENTORYORDER_FAIL";

export const DELETE_INVENTORYORDER_REQUEST = "DELETE_INVENTORYORDER_REQUEST";
export const DELETE_INVENTORYORDER_SUCCESS = "DELETE_INVENTORYORDER_SUCCESS";
export const DELETE_INVENTORYORDER_RESET = "DELETE_INVENTORYORDER_RESET";
export const DELETE_INVENTORYORDER_FAIL = "DELETE_INVENTORYORDER_FAIL";

export const INVENTORYORDER_DETAILS_REQUEST = "INVENTORYORDER_DETAILS_REQUEST";
export const INVENTORYORDER_DETAILS_SUCCESS = "INVENTORYORDER_DETAILS_SUCCESS";
export const INVENTORYORDER_DETAILS_FAIL = "INVENTORYORDER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
