export const CREATE_INVENTORYORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_INVENTORYORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_INVENTORYORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_INVENTORYORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_INVENTORYORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_INVENTORYORDERS_FAIL = "MY_ORDERS_FAIL";

export const ALL_INVENTORYORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_INVENTORYORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_INVENTORYORDERS_FAIL = "ALL_ORDERS_FAIL";

export const UPDATE_INVENTORYORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_INVENTORYORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_INVENTORYORDER_RESET = "UPDATE_ORDER_RESET";
export const UPDATE_INVENTORYORDER_FAIL = "UPDATE_ORDER_FAIL";

export const DELETE_INVENTORYORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_INVENTORYORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_INVENTORYORDER_RESET = "DELETE_ORDER_RESET";
export const DELETE_INVENTORYORDER_FAIL = "DELETE_ORDER_FAIL";

export const INVENTORYORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const INVENTORYORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const INVENTORYORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
